export { default as Admin } from './Home';
export { default as Home } from './Welcome';
export { default as Login } from './Login';
export { default as States } from './States';
export { default as Lgas } from './Lgas';
export { default as Areas } from './Areas';
export { default as Streets } from './Streets';
export { default as Incidences } from './Incidences';
export { default as NotFound } from './NotFound';
